### ISSUE TITLE
State of this feature and further plans

### ISSUE THREAD

**Issue by jschpp** [mumble-voip/mumble-streamdeck-integration#1] opened 2021-02-22 09:48 UTC
Since I was looking for this I'm curious if this feature is no longer planned?

If you still want to go ahead with it how would you go about it and is there anything that could be done to help?

**Comment by Krzmbrzl** [comment] 2021-02-22 10:13
I am still planning on working on this. It is not my top priority though and since I did come across a couple of things that were further up my priority list, development of this feature made a small break.

I actually have a working prototype of this feature locally on my PC. For now it only provides support for muting and deafening yourself via buttons on the StreamDeck.

Before I add the sources here though, I have to fix the failing test-case on Windows of https://github.com/mumble-voip/mumble-json-bridge/pull/2 as the changes from there are required for the integration to work.
If you happen to have the motivation and/or knowledge, I'd appreciate it, if you could have a look at the cause of the failure (it is some sort of stack corruption that happens at a certain position, but I don't understand why. I'll describe it in more detail, if you are interested).

And as a final note: The integration will require plugin support on Mumble's side which will be introduced in 1.4.0 via https://github.com/mumble-voip/mumble/pull/3743

**Comment by jschpp** [comment] 2021-03-16 12:14
I tried looking into it and I don't have the knowledge to fix it. Sorry 😅

**Comment by Krzmbrzl** [comment] 2021-03-16 13:41
No worries :)
Thanks for trying though :+1:

I expect to get to work on this again in the upcoming weeks...

**Comment by Krzmbrzl** [comment] 2021-03-25 20:01
I think I have fixed the mentioned issue...

In any case, you can follow the development progress of the stream deck plugin in #2

**Comment by Krzmbrzl** [comment] 2021-04-04 19:07
Okay the first prototype is working now and just got merged.
If you are feeling adventurous and capable of building Mumble from Source (still required at this point) you can test it out for yourself.

Let me know if you have further questions :)

**Closed as completed by Krzmbrzl** 2021-04-04 19:07 UTC

**Comment by Krzmbrzl** [comment] 2021-04-18 18:27
Plugin support has now been merged into Mumble's master branch. Therefore starting with the development snapshot 5 of the 1.4.0 version this plugin will actually be usable without having to compile Mumble yourself.

**Comment by jschpp** [comment] 2021-04-19 05:43
That would certainly help deploying it within our corporate env :-) Thank you for your work
